# Generated by Django 3.2.4 on 2021-06-24 02:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Seccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Ejercicio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.ImageField(upload_to='')),
                ('nombre_ejercicio', models.CharField(max_length=30)),
                ('descripcion_ejercicio', models.CharField(max_length=500)),
                ('pasos', models.CharField(max_length=1000)),
                ('fecha', models.DateField(auto_now=True)),
                ('seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Registro.seccion')),
            ],
        ),
    ]
