# Generated by Django 3.2.4 on 2021-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='descripcion_ejercicio',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='ejercicio',
            name='pasos',
            field=models.TextField(),
        ),
    ]
