# Generated by Django 3.2.4 on 2021-06-25 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0004_ejercicio_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='section',
            field=models.CharField(choices=[('ABDOMEN', 'ABDOMEN'), ('ESPALDA', 'ESPALDA'), ('PECHO', 'PECHO'), ('BRAZO', 'BRAZO')], default='-----', max_length=15),
        ),
    ]
