# Generated by Django 3.2.4 on 2021-06-25 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0005_alter_ejercicio_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ejercicio',
            name='seccion',
        ),
        migrations.DeleteModel(
            name='Seccion',
        ),
    ]
