# Generated by Django 3.2.5 on 2021-07-06 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0007_alter_ejercicio_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='section',
            field=models.CharField(choices=[('NONE', 'NONE'), ('ABDOMEN', 'ABDOMEN'), ('ESPALDA', 'ESPALDA'), ('PECHO', 'PECHO'), ('BRAZO', 'BRAZO')], default='NONE', max_length=15),
        ),
    ]
