# Generated by Django 3.2.5 on 2021-07-08 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0008_alter_ejercicio_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(null=True, upload_to='ejerciciofoto'),
        ),
    ]
