# Generated by Django 3.2.4 on 2021-06-25 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registro', '0006_auto_20210624_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ejercicio',
            name='imagen',
            field=models.ImageField(upload_to='ejerciciofoto'),
        ),
    ]
